### ISSUE TITLE
...error creating ephemeral docker network...could not find...an IPv4 address pool...

### ISSUE THREAD

**Issue by feuGeneA** [CircleCI-Archived/local-cli#40]
I have a project that's building and testing itself very nicely in the hosted CircleCI service.  However, I'm having trouble using `local-cli` with the project:

```
$ file .circleci/config.yml 
.circleci/config.yml: ASCII text
$ circleci local execute
Docker image digest: sha256:3d88cfffd448da07ff8ced22ccdca5adc09ff18e87dc7db9b8af5b8a47647c08
====>> Spin up Environment
Build-agent version 0.1.750-336e0196 (2018-09-13T19:48:06+0000)
Error: 
Unexpected environment preparation error: error creating ephemeral network bridge: error creating ephemeral docker network: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network

Step failed
Task failed
Error: error creating ephemeral network bridge: error creating ephemeral docker network: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network
```

What further info can I gather for you?

**Comment by dnephin** [comment]
This error means that docker has reached its bridge network limit. We have a plan for working around this limit, but it will require some larger changes, so it won't be available for a while. 

You can probably work around this limit by doing the following:
1. Run `docker network ls | grep bridge` to see a full list of the networks
2. Any networks that you aren't currently using can be removed with `docker network rm`

After removing at least one network you should be able to run `local execute` once again.

**Comment by zzak** [comment]
Thanks for your report @feuGeneA!

Please let us know if Daniel's suggestion helps, or file a ticket on [the new CLI issue tracker](https://github.com/CircleCI-Public/circleci-cli/issues/new).
